### ISSUE TITLE
delete and task status issue

### ISSUE THREAD

**Issue by DoM1No7773** [GeFeC/Flask-todo#3]
w aplikacji nie działa delete oraz po odświeżeniu strony, gdy zaznaczy się 
wcześniej 'start' lub 'finish' zmiany nie są zapisywane do bazy.

bład w terminalu:

```bash
172.17.0.1 - - [30/Nov/2022 14:11:27] "PUT / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app.py", line 47, in index_put
    task = db.get_or_404(Task, req["id"])
KeyError: 'id' 
```

**Comment by GeFeC** [comment]
Naprawione
